import java.io.*;import java.util.*;
/** JSON-lines adapter; Python sends topology and receives traversal results. */
public final class Main {
    public static void main(String[] args){try{String input=new BufferedReader(new InputStreamReader(System.in)).readLine();if(input==null)throw new IllegalArgumentException("Expected one JSON request on stdin");NetworkGraph g=new NetworkSimulator().build(input);String start=value(input,"start","T01");long t=System.nanoTime();List<String> dfs=new DFS().traverse(g,start);long dfsMs=(System.nanoTime()-t)/1_000_000;t=System.nanoTime();List<List<String>> levels=new BFS().levels(g,start);long bfsMs=(System.nanoTime()-t)/1_000_000;Set<String> reached=new LinkedHashSet<>();for(List<String> level:levels)reached.addAll(level);List<String> affected=new ArrayList<>();for(Node n:g.getNodes())if(!reached.contains(n.getId()))affected.add(n.getId());List<String> down=new ArrayList<>();for(Link l:g.getLinks())if(!l.isUp())down.add(l.getId());String destination=value(input,"destination",null);List<String> route=destination==null?Collections.emptyList():shortestPath(g,start,destination);System.out.println("{\"dfs_path\":"+json(dfs)+",\"bfs_levels\":"+json2(levels)+",\"visited_nodes\":"+json(new ArrayList<>(reached))+",\"affected_nodes\":"+json(affected)+",\"affected_links\":"+json(down)+",\"route_path\":"+json(route)+",\"dfs_time_ms\":"+dfsMs+",\"bfs_time_ms\":"+bfsMs+"}");}catch(Exception e){System.err.println(e.getMessage());System.exit(2);}}
    private static List<String> shortestPath(NetworkGraph graph,String source,String destination){if(graph.getNode(source)==null||graph.getNode(destination)==null)return Collections.emptyList();Map<String,String> previous=new HashMap<>();Set<String> seen=new HashSet<>();Queue<String> queue=new ArrayDeque<>();queue.add(source);seen.add(source);while(!queue.isEmpty()){String current=queue.remove();if(current.equals(destination))break;for(Link link:graph.getNode(current).getLinks()){String next=link.other(current);if(link.isUp()&&seen.add(next)){previous.put(next,current);queue.add(next);}}}if(!seen.contains(destination))return Collections.emptyList();List<String> path=new ArrayList<>();for(String at=destination;at!=null;at=previous.get(at))path.add(at);Collections.reverse(path);return path;}
    private static String value(String s,String k,String d){java.util.regex.Matcher m=java.util.regex.Pattern.compile("\\\""+k+"\\\"\\s*:\\s*\\\"([^\\\"]+)\\\"").matcher(s);return m.find()?m.group(1):d;}
    private static String q(String s){return "\""+s.replace("\\","\\\\").replace("\"","\\\"")+"\"";}
    private static String json(List<String>a){List<String>o=new ArrayList<>();for(String s:a)o.add(q(s));return "["+String.join(",",o)+"]";}
    private static String json2(List<List<String>>a){List<String>o=new ArrayList<>();for(List<String>s:a)o.add(json(s));return "["+String.join(",",o)+"]";}
}
