"""Analytics page computed from actual session incidents and model metrics."""
from __future__ import annotations
import pandas as pd
import streamlit as st
from python_engine.predictive_engine import predict_maintenance
from python_engine.resilience import calculate_resilience

FAULTS = ["Fiber Link Failure", "Tower Power Failure", "Hardware Failure", "High Latency", "Packet Loss", "Signal Degradation", "Network Congestion", "Normal"]

def render_analytics(incidents: list[dict], saved_events: list[dict], nodes: list[dict], links: list[dict], metrics: dict, generate_demo) -> None:
    st.subheader("NOC Analytics")
    if not incidents:
        st.info("No simulated incidents have been recorded in this session. Generate real synthetic diagnoses to populate the charts and metrics.")
        if st.button("Generate demo incident dataset", type="primary"):
            generate_demo()
            st.rerun()
        st.caption("The demo set is generated by running each fault profile through the same rules, ML, anomaly and Java graph pipeline.")
        return
    frame = pd.DataFrame(incidents)
    total = len(frame); critical = int((frame["severity"] == "CRITICAL").sum()); major = int((frame["severity"] == "MAJOR").sum()); normal = int((frame["fault_type"] == "Normal").sum())
    avg_ms = float(frame["diagnosis_time_ms"].mean()); avg_conf = float(frame["confidence"].mean())
    a, b, c, d, e = st.columns(5)
    a.metric("TOTAL INCIDENTS", total); b.metric("CRITICAL", critical); c.metric("MAJOR", major); d.metric("NORMAL EVENTS", normal); e.metric("AVG CONFIDENCE", f"{avg_conf:.1%}")
    st.markdown("#### Fault distribution")
    distribution = frame["fault_type"].value_counts().reindex(FAULTS, fill_value=0).rename_axis("Fault type").rename("Count").reset_index()
    st.bar_chart(distribution.set_index("Fault type"))
    st.dataframe(distribution, hide_index=True, width="stretch")
    st.markdown("#### Diagnosis performance")
    x, y, z, w = st.columns(4)
    x.metric("AVERAGE", f"{avg_ms:.2f} ms"); y.metric("MINIMUM", f"{frame['diagnosis_time_ms'].min()} ms"); z.metric("MAXIMUM", f"{frame['diagnosis_time_ms'].max()} ms"); w.metric("HIGHEST CONFIDENCE", f"{frame['confidence'].max():.1%}")
    severity = frame["severity"].value_counts().rename_axis("Severity").rename("Count").reset_index()
    st.bar_chart(severity.set_index("Severity"))
    st.markdown("#### ML evaluation · synthetic holdout")
    report = pd.DataFrame(metrics["report"]).T
    metric_cols = st.columns(4)
    for col, key in zip(metric_cols, ("accuracy", "precision_macro", "recall_macro", "f1_macro")):
        col.metric(key.replace("_", " ").upper(), f"{float(metrics.get(key, metrics.get('accuracy', 0))):.1%}")
    st.dataframe(report.round(3), width="stretch")
    st.caption("Model scores use a stratified holdout from generated synthetic telemetry; they are not production accuracy claims.")
    st.write("Confusion matrix · rows actual, columns predicted")
    st.dataframe(pd.DataFrame(metrics["matrix"], index=metrics["labels"], columns=metrics["labels"]), width="stretch")
    st.markdown("#### Anomaly detections")
    statuses = [event.get("evidence", {}).get("anomaly", {}).get("status", "NORMAL") for event in incidents]
    anomaly_counts = pd.Series(statuses).value_counts().reindex(["NORMAL", "SUSPICIOUS", "ANOMALOUS"], fill_value=0).rename_axis("Anomaly status").rename("Count").reset_index()
    st.bar_chart(anomaly_counts.set_index("Anomaly status")); st.dataframe(anomaly_counts, hide_index=True, width="stretch")
    latest_event = saved_events[0] if saved_events else None
    live_links = latest_event.get("links", links) if latest_event else links
    graph = latest_event.get("incident", {}).get("graph_result", {}) if latest_event else {}
    affected = set(graph.get("affected_nodes", []))
    down_count = sum(link.get("status") != "UP" for link in live_links)
    health = round(100 * len(graph.get("visited_nodes", [node["tower_id"] for node in nodes])) / max(1, len(nodes)) * (1 - down_count / max(1, len(live_links))))
    st.markdown("#### Network analytics")
    route_available = bool(graph.get("route_path")) if graph else True
    resilience = calculate_resilience(graph or {"visited_nodes": [node["tower_id"] for node in nodes]}, nodes, live_links, route_available)
    ncols = st.columns(6)
    ncols[0].metric("TOWERS", len(nodes)); ncols[1].metric("ACTIVE LINKS", len(live_links) - down_count); ncols[2].metric("AFFECTED TOWERS", len(affected)); ncols[3].metric("UNREACHABLE TOWERS", len(graph.get("affected_nodes", []))); ncols[4].metric("NETWORK HEALTH", f"{health}%"); ncols[5].metric("RESILIENCE", f"{resilience['score']}% · {resilience['label']}")
    st.caption(resilience["formula"])
    st.markdown("#### Prototype Predictive Maintenance")
    st.caption("Prototype using synthetic telemetry — not production maintenance prediction.")
    risk_rows = []
    for node in nodes:
        tower = node["tower_id"]
        history = [{"tower_id": tower, "temperature": node.get("temperature", 40), "cpu_load": node.get("cpu_load", .3), "signal_strength": node.get("signal_strength", .85), "latency_ms": 20, "packet_loss": .5, "error_rate": .2}]
        for saved in saved_events:
            event = saved["incident"]
            if saved["telemetry"].get("affected_node") == tower:
                history.append({**saved["telemetry"], "tower_id": tower, "anomaly_status": event.get("evidence", {}).get("anomaly", {}).get("status")})
        risk = predict_maintenance(tower, history)
        risk_rows.append({"Tower": tower, "Risk": risk["score"], "Category": risk["category"], "Contributing factors": ", ".join(risk["factors"]), "Recommended action": risk["action"]})
    st.dataframe(pd.DataFrame(risk_rows), hide_index=True, width="stretch")
    st.bar_chart(pd.DataFrame(risk_rows).set_index("Tower")[["Risk"]])
    st.markdown("#### Incident timeline")
    timeline = frame.copy(); timeline["timestamp"] = pd.to_datetime(timeline["timestamp"], errors="coerce", utc=True); timeline = timeline.dropna(subset=["timestamp"]).sort_values("timestamp").set_index("timestamp")
    if not timeline.empty:
        st.line_chart(timeline[["confidence"]]); st.dataframe(frame[["incident_id", "timestamp", "fault_type", "severity", "confidence", "diagnosis_time_ms"]], hide_index=True, width="stretch")
